name: mobile_starter_kit
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: any
  collection: ^1.16.0
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.2
  go_router: ^5.2.4

  #store
  provider: ^6.0.4
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.3

  # networking
  http: ^0.13.5
  dio: ^4.0.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  mobx_codegen: ^2.1.1
  # networking
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/movies/
    - assets/images/users/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
